### ISSUE TITLE
Consider a more natural API syntax

### ISSUE THREAD

**Issue by jhuckabee** [mikeyhogarth/duckpond#1]
This is a neat gem. I found it on your Reddit Gimme Gem Thursdays post. While reading through the documentation the API felt a little backwards and confusing to me. Your documentation explains that you can check to see "if the contract is fulfilled by the object" using the `fulfills?` method. The `fulfills?` method feels like it belongs on the object being checked, not the contract:

`"Hello".fulfills?(MyContract)`

Or, perhaps if we really want to ask the contract, just rename the `fulfills?` method to be more in line with the natural description of what it is doing:

`MyContract.is_fulfilled_by?("Hello")`  or just `MyContract.fulfilled_by?("Hello")`

Something to consider.

**Comment by mikeyhogarth** [comment]
Thank you! Yeah it's been a while since I worked on this but with fresh eyes you are totally correct. I'll maybe put in an alias when I get a chance.

**Comment by anthonylebrun** [comment]
+1 for the `MyContract.fulfilled_by?("Hello")` syntax. I'll submit a pull request.

**Comment by mikeyhogarth** [comment]
Fixed
